---
title: "Tidy Tuesday"
author: "Ethan Tenison"
date: "`r format(Sys.Date(), '%B %d, %Y') `"
output:
  bookdown::html_document2:
    toc: yes
    toc_float: yes
    toc_depth: 3
    collapsed: yes
    number_sections: yes
    fig_caption: yes
always_allow_html: yes
editor_options:
  chunk_output_type: console

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())


library(shiny) #Dashboard/html viewer
library(bookdown)#Book making/html convert
library(kableExtra)#table renderer
library(flextable)#table renderer
library(readr)
library(tidyverse)


```


# Animal Rescues 2021-06-29

The data this week comes from [London.gov](https://data.london.gov.uk/dataset/animal-rescue-incidents-attended-by-lfb) by way of Data is Plural and Georgios Karamanis.


# Kable Package to visualize table 

London provides a ton of data about animal rescues including time, location, animal type, total hours it took for rescue, and many more. 


```{r animal_rescue-dataexplor, message=FALSE, warning=FALSE, echo = FALSE}
animal_rescues <- read_csv("data/raw/animal_rescues.csv")

animal_rescues[ sample.int(10),] |> 
  kbl() |> 
  kable_styling(bootstrap_options = c("striped", "hover")) |>  
  scroll_box(width = "100%", height = "500px")

```

# Geospatial 

```{r geospatial}
library(sf)
library(convert)

#About half of cases do not have spatial coordinates and they have been removed 
spatial <- animal_rescues |> 
  mutate(latitude = replace(latitude, latitude == "NULL", NA)) |> 
  drop_na(latitude) |> 
  mutate(latitude = as.numeric(latitude),
         longitude = as.numeric(longitude)) |> 
  filter(latitude >10)



ggplot() +
  geom_point(data = spatial, aes(x = latitude, y = longitude)) 



```